# Generated by Django 5.0.14 on 2026-01-29 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Image',
            field=models.ImageField(default='admin.png', upload_to='user/'),
        ),
    ]
