# Generated by Django 5.0.14 on 2026-01-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_users_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Role',
            field=models.CharField(default='User', max_length=50),
        ),
    ]
