# Generated by Django 5.0.14 on 2026-02-06 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_users_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('p_des', models.TextField()),
                ('price', models.CharField(max_length=10)),
                ('p_image', models.ImageField(upload_to='product/')),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='Image',
            field=models.ImageField(default='user.png', upload_to='user/'),
        ),
    ]
