# Generated by Django 6.0.2 on 2026-02-23 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_products_alter_users_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='isCart',
            field=models.BooleanField(default=False),
        ),
    ]
