# Generated by Django 6.0.2 on 2026-02-24 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_products_iscart'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('pr_id', models.IntegerField()),
            ],
        ),
    ]
